server {
    listen 8080;
    server_name local.com;
    client_max_body_size 20;

    root ./www;
    autoindex off;
    index index.html;

    # Diretivas da Issue atual
    error_page 404 /404.html;
    error_page 403 /403.html;
    error_page 413 /413.html;

    location /files/ {
        root ./www/arquivos_pesados;
        autoindex on;
    }

    location /scripts/ {
        root ./www/;
        autoindex on;
        cgi_ext .py;
        cgi_pass /opt/homebrew/bin/python3;
    }
}

server {
    listen 8080;
    server_name meuteste.com;
    root ./www/teste_host;
    autoindex off;
    index index.html;
}

