server {
	listen 8080;
	server_name local.com;

	# Regra Global do servidor
	root ./www;
	autoindex off;
	index index.html;

	# Regra Exclusiva para a pasta de arquivos
	location /files/ {
		root ./www/arquivos_pesados;
		autoindex on;
	}
}

server {
	listen 8080;
	server_name meuteste.com;
	root ./www/teste_host;
	autoindex off;
	index index.html;
}
