server {
    listen 8080;
    server_name local.com;
    
    # Limite aumentado para 20 Megabytes para evitar o erro 413 no teste
    client_max_body_size 10; 
    
    # Regras Globais do servidor
    root ./www;
    autoindex off;
    index index.html;
    
    # Paginas de erro customizadas
    error_page 404 /404.html;
    error_page 403 /403.html;
    error_page 413 /413.html;

    # Testes de Redirecionamento
    location /google {
        return 301 http://www.google.com;
    }

    location /novo/ {
        return 302 /files/;
    }

    # Regra Exclusiva para a rota alvo do upload
    location /files/ {
        root ./www/arquivos_pesados;
        autoindex on;
        
        # Destino fisico onde os arquivos de POST serao armazenados
        upload_store ./www/arquivos_pesados/files;
    }

    location /scripts/ {
        root ./www/;
        autoindex on;
        cgi_ext .py;
        cgi_pass /usr/bin/python3;
    }
}

# Virtual Host de teste
server {
    listen 8080;
    server_name meuteste.com;
    root ./www/teste_host;
    autoindex off;
    index index.html;
}

